### ISSUE TITLE
Hi! is there any mysql working example?, the demo works lika a charm with arrays but i can't see it in action wiht mysql tables. Any help? Thank's in advance. Congratulations for this beautiful piece of code.

### ISSUE THREAD

**Issue by sirjulian1959** [basarevych/dynamic-table#1]

**Comment by basarevych** [comment]
What exactly the example you need? php and pdo mysql?

**Comment by sirjulian1959** [comment]
El 12/02/2016 a las 6:31, Ross Basarevych escribió:

> What exactly the example you need? php and pdo mysql?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/basarevych/dynamic-table/issues/1#issuecomment-183185563.
> 
> Hi Ross, first of all thanks for your quick answer! and yes it will be 
> nice to see a php and pdo mysql example in action.

Cheers!
Julian

**Comment by basarevych** [comment]
hang on, just found a couple of bugs there. I'm a bit busy now but in a day or two I will roll out new release and demos.

**Comment by basarevych** [comment]
the new release is here, please follow the updated README
